### ISSUE TITLE
Does not work with Snakemake v8

### ISSUE THREAD

**Issue by levlitichev** [Snakemake-Profiles/lsf#62]
This profile is incompatible with Snakemake version 8 because the `--cluster` command line arguments were deprecated (more information [here](https://snakemake.readthedocs.io/en/latest/getting_started/migration.html#migrating-to-snakemake-8)).

[Here](https://github.com/Snakemake-Profiles/slurm/issues/117) is this same issue being discussed on the slurm profile Github.

I understand this package is no longer being actively maintained, but I thought I would leave a note in case it's helpful to someone in the future.

Snakemake version 7 still works fine with this profile (more specifically, I'm using v7.32.4).

**Comment by dlaehnemann** [comment]
For snakemake version 8 upwards, you will have to use an executor plugin on cluster systems, instead of a profile like this one. There's one being developed for LSF, have a look here:
https://github.com/BEFH/snakemake-executor-plugin-lsf/

Also, there's a thread about it on Discord, for a more interactive discussion:
https://discord.com/channels/753690260830945390/1204469412065837066

Profiles will then rather contain user- and hardware-specific settings, while the executor plugins abstract away all the cluster system API...

**Comment by levlitichev** [comment]
I see -- thank you for the links.

**Comment by dlaehnemann** [comment]
Thanks for raising this, that way we have this "documented" here. :sweat_smile:
